language: java
jdk:
  - oraclejdk8
  - oraclejdk11

before_install:
  - chmod +x gradlew

addons:
  sonarcloud:
    organization: "eobermuhlner"
    token:
      secure: CEJ5KV9LrTVLS+eIvH+r78TrIqxfveslqYC4GL3qJ6rvjlkDn7mhTw0e5peqg2Syb61ZyscdkzAYZ3M7NkIw1bBHuLr/XBIW8FY6gwTuSxNkAkLQ0YKDXbENxve9lwJ4LtcNTqBMYjta3tCCuhWGKnMiTv+5ga4p+PWEeKJXkiL+lDgV4/VRya4omaF/8TfMi4WpdiOG09vQwqg9TOl5vgr+AX71zQ8l8AxW4hKdA7ofadgLcSBvspJs7cv/sdkXMG4gw405PvlK27JIWlvlX/Sc2zRRYkso1k6LgwavcetGneN2DyOCpuqtwd9ORQWjlPq1hpEN8fZpgEJTc4JfXtk5eA2qF72m9zcaua12diJwfvQt1z7gIaabkZVeQFMNRjLZVREAdNR/0MChIB0BR90aPA2O1XP7bJwEzLdf4YehtRdpHgZav6jh84+8qxNwsZkNFz/MymMFzlysIJVfylPXZYdeokuNGoFXWJfnS5shHmNwBQQHsCK9+KzuO3nymE0dMqQXjB4NJGPXrE84WAG2bp+BQJjfiPB8VrBP/e9KhlvqmF58Q2BteV8ftVWERe9CoIFwWpkjKfkDUx72PK1vcpOPYLNWlAmz56A4ao+fLJnl4taHlgvodVdatw3vm2BZ5BIQkX2SxnBRaaD26x+U4+oLl/IHCsNIhZl5DlE=

script:
  - ./gradlew sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)

# set sudo to required, because this setup gets more memory
sudo: required

# keep gradle cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
